apiVersion: v2
name: qovery-deploy-gate
description: Zero-config synchronized traffic cutover for multi-service deployments on Qovery/Kubernetes
version: 1.0.1
appVersion: "1.0.1"
type: application
dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
